apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: vscode-cpp-cling
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: >-
      https://github.com/nerc-images/vscode-cpp-cling
    opendatahub.io/notebook-image-name: >-
      VSCode C++ Cling
    opendatahub.io/notebook-image-desc: >-
      An OpenShift AI Image running VSCode for C++ development.
      - Based on the [Xeus Cling project](https://github.com/jupyter-xeus/xeus-cling)
      on GitHub for Jupyter Lab Notebook integration.
      - Uses C++ Kernel 11, 14, and 17 and gcc-c++ compiler support.
      - Used by Professor Leonidas Kontothanassis, MassMutual Professor of the
      Practice of Computing & Data Sciences + Director of Industry Engagement.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 1.0.0
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/nerc-images/vscode-cpp-cling:1.0.0'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
