apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: ai-telemetry-workbench
  namespace: redhat-ods-applications
  labels:
    opendatahub.io/notebook-image: "true"
  annotations:
    opendatahub.io/notebook-image-url: >-
      https://github.com/nerc-images/ai-telemetry-workbench
    opendatahub.io/notebook-image-name: >-
      AI Telemetry workbench
    opendatahub.io/notebook-image-desc: >-
      An OpenShift AI Image for Java and Go development.
      Contains all the dependencies to run develop AI Telemetry
      and the Prometheus Keycloak Proxy for fine-grained access
      control to Red Hat ACM Observability metrics.
spec:
  lookupPolicy:
    local: true
  tags:
    - name: 1.1.0
      annotations: null
      from:
        kind: DockerImage
        name: 'quay.io/nerc-images/ai-telemetry-workbench:1.1.0'
      importPolicy:
        scheduled: true
      referencePolicy:
        type: Source
