apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../imagestreams/cuda-jupyter-tensorflow
  - ../../imagestreams/jupyter-cpp-cling
  - ../../imagestreams/jupyter-rust
  - ../../imagestreams/vscode-cpp-cling
  - ../../imagestreams/vscode-java
  - ../../imagestreams/vscode-rust
  - ../../imagestreams/openad_workbench
  - ../../imagestreams/rclone
  - ../../imagestreams/anythingllm
  - ../../imagestreams/rstudio
  - ../../imagestreams/altastata-jupyter-datascience
